### ISSUE TITLE
Good news: After a long time, the migration will be done this weekend

### ISSUE THREAD

**Issue by Neustradamus** [jabber2/jabberdotorg#3]
Good news: After several years, the migration will be done this weekend:
- https://mail.jabber.org/pipermail/juser/2023-January/007189.html

Linked to:
- https://github.com/stpeter/jabberdotorg/issues/28
- https://github.com/stpeter/jabberdotorg/issues/27
- https://github.com/stpeter/jabberdotorg/issues/26
- https://github.com/stpeter/jabberdotorg/issues/23
- https://github.com/stpeter/jabberdotorg/issues/21
- https://github.com/stpeter/jabberdotorg/issues/20
- https://github.com/stpeter/jabberdotorg/issues/17
- https://github.com/stpeter/jabberdotorg/issues/16
- https://github.com/stpeter/jabberdotorg/issues/9
- https://github.com/stpeter/jabberdotorg/issues/7
- https://github.com/stpeter/jabberdotorg/issues/6
- https://github.com/stpeter/jabberdotorg/issues/3

**Comment by stpeter** [comment]
@Neustradamus Mind your own business.

**Comment by Neustradamus** [comment]
@stpeter, @mwild1: Good job for the migration of active users.
- https://mail.jabber.org/pipermail/juser/2023-January/date.html
